### ISSUE TITLE
[Help Wanted] 关于多人游戏服务端封包封包溯源

### ISSUE THREAD

**Issue by ExerciseBook** [NPLPackages/paracraft#83]
于 https://github.com/NPLPackages/paracraft/blob/master/script/apps/Aries/Creator/Game/Network/NetServerHandler.lua#L263 可见有方块同步处理逻辑。

我想询问一下此处的 `packet_BlockChange` 是否可以获取到对应的操作用户。我想在游玩的时候对玩家的行为作出一点限制。（比如说白名单，方块禁用啦）

**Comment by LiXizhi** [comment]
https://github.com/NPLPackages/paracraft/blob/master/script/apps/Aries/Creator/Game/Network/NetServerHandler.lua#L46-L49

这里是玩家的信息， 每个玩家都有一个NetServerHandler. 
不过这个功能是打算做的， 还没有开发出来。 

如果能写， 可以考虑提交Pull Request (PR) 给我们。

**Comment by ExerciseBook** [comment]
好的，了解了。感谢解答。
